import type { SocialClip } from '../types'

export const MOCK_CLIPS: SocialClip[] = [
  {
    id: 'mock-1',
    debateId: 'debate-mock-1',
    createdBy: 'system',
    type: 'highlight',
    title: 'Free Speech vs Platform Moderation',
    hookText: 'Can free speech\nbe regulated online?',
    claimText: 'Platforms need strict content policies to protect users from coordinated harm.',
    counterText: 'Any censorship sets a precedent that erodes free expression for everyone.',
    resultText: '61% sided with regulation after hearing the full arguments.',
    argumentIds: [],
    crowdVoteResult: '61% voted FOR regulation',
    cardImageUrl: null,
    cardTemplate: 'dark',
    debateTitle: 'Should social media platforms regulate speech?',
    topicCategory: 'Culture & Trends',
    forUsername: 'modpolicy',
    againstUsername: 'freespeech_max',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    shareCount: 412,
  },
  {
    id: 'mock-2',
    debateId: 'debate-mock-2',
    createdBy: 'system',
    type: 'result',
    title: 'Remote Work Is the Future',
    hookText: 'Is remote work\nkilling company culture?',
    claimText: 'In-person collaboration drives innovation — remote work creates invisible silos.',
    counterText: 'The best talent doesn\'t live in your city. Remote work wins the talent war.',
    resultText: 'Crowd was split 52/48 — the closest debate this month.',
    argumentIds: [],
    crowdVoteResult: '52% voted AGAINST remote work killing culture',
    cardImageUrl: null,
    cardTemplate: 'vibrant',
    debateTitle: 'Does remote work hurt company culture more than it helps?',
    topicCategory: 'Business & Money',
    forUsername: 'officefirst_dev',
    againstUsername: 'remote_rox',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    shareCount: 289,
  },
  {
    id: 'mock-3',
    debateId: 'debate-mock-3',
    createdBy: 'system',
    type: 'bestOf',
    title: 'Cardio vs Lifting',
    hookText: 'What\'s actually\nbetter for longevity?',
    claimText: 'Zone 2 cardio for 150 min/week cuts all-cause mortality risk by 35%. The data is clear.',
    counterText: 'Muscle mass is the #1 predictor of healthspan past 50. Lift heavy, live longer.',
    resultText: '38 people switched their stance mid-debate.',
    argumentIds: [],
    crowdVoteResult: '57% voted FOR strength training',
    cardImageUrl: null,
    cardTemplate: 'light',
    debateTitle: 'Cardio vs Strength Training: Which matters more for longevity?',
    topicCategory: 'Fitness & Health',
    forUsername: 'zone2_pete',
    againstUsername: 'liftforlife',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    shareCount: 731,
  },
  {
    id: 'mock-4',
    debateId: 'debate-mock-4',
    createdBy: 'system',
    type: 'highlight',
    title: 'UBI Would Break the Economy',
    hookText: 'Would universal\nbasic income work?',
    claimText: 'UBI eliminates poverty traps, funds human creativity, and costs less than the current welfare bureaucracy.',
    counterText: 'Unconditional cash at scale is inflationary. It\'s never worked without cratering labor supply.',
    resultText: '44% changed their mind — one of the most persuasive debates on record.',
    argumentIds: [],
    crowdVoteResult: '55% voted FOR UBI',
    cardImageUrl: null,
    cardTemplate: 'dark',
    debateTitle: 'Should the US implement Universal Basic Income?',
    topicCategory: 'Business & Money',
    forUsername: 'ubi_advocate',
    againstUsername: 'fiscal_hawk',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    shareCount: 905,
  },
  {
    id: 'mock-5',
    debateId: 'debate-mock-5',
    createdBy: 'system',
    type: 'result',
    title: 'The Trolley Problem, Revisited',
    hookText: 'Pull the lever\nor do nothing?',
    claimText: 'Inaction is still a choice. Pulling the lever minimizes harm — utilitarian math is clear.',
    counterText: 'You cannot use a person as a means to an end. Pulling the lever makes you a killer.',
    resultText: 'The crowd was 50/50 — no consensus reached.',
    argumentIds: [],
    crowdVoteResult: '50% voted PULL / 50% voted DO NOTHING',
    cardImageUrl: null,
    cardTemplate: 'vibrant',
    debateTitle: 'Trolley Problem: Is pulling the lever morally justified?',
    topicCategory: 'Hypotheticals & Moral Dilemmas',
    forUsername: 'util_sam',
    againstUsername: 'kant_enjoyer',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    shareCount: 1203,
  },
  {
    id: 'mock-6',
    debateId: 'debate-mock-6',
    createdBy: 'system',
    type: 'bestOf',
    title: 'AI Will Take Your Job',
    hookText: 'Is AI coming\nfor your career?',
    claimText: 'Within 10 years, 40% of white-collar jobs will be automated. We are unprepared.',
    counterText: 'Every technology wave creates more jobs than it destroys. AI is no different.',
    resultText: '29 people switched sides. The AI optimists barely held on.',
    argumentIds: [],
    crowdVoteResult: '54% voted AI WILL displace net jobs',
    cardImageUrl: null,
    cardTemplate: 'dark',
    debateTitle: 'Will AI cause net job losses within the next decade?',
    topicCategory: 'Culture & Trends',
    forUsername: 'ai_doomer99',
    againstUsername: 'tech_optimist',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    shareCount: 2147,
  },
]
